<?php declare(strict_types=1);

const SITE_DB_PATH = ':memory:';
const SITE_BASE_PATH = '';
const APP_IDENTITY_FIELD = 'bundle_identifier';
const API_TOKENS = ['ordinary-token'=>'agent:external','trusted-token'=>['identity'=>'agent:owner','trusted'=>TRUE]];
const COMPATIBILITY_STATES = ['?????'=>'unknown','*XXXX'=>'one failed','*????'=>'one unknown','**XXX'=>'two failed','**???'=>'two unknown','***XX'=>'three failed','***??'=>'three unknown','****X'=>'four failed','****?'=>'four unknown','*****'=>'five'];
const RATINGS = [0=>['symbol'=>'?','description'=>'unknown'],1=>['symbol'=>'*','description'=>'one'],2=>['symbol'=>'**','description'=>'two'],3=>['symbol'=>'***','description'=>'three'],4=>['symbol'=>'****','description'=>'four'],5=>['symbol'=>'*****','description'=>'five']];
const APP_EXTRA_FIELDS = ['bundle_identifier'=>['name'=>'Bundle ID','required'=>TRUE],'developer_publisher'=>['name'=>'Publisher'],'release_year'=>['name'=>'Year']];
const VERSION_EXTRA_FIELDS = ['bundle_version'=>['name'=>'Build','required'=>TRUE],'short_version'=>['name'=>'Short'],'minimum_os_version'=>['name'=>'Minimum OS'],'app_artifact_sha256'=>['name'=>'App hash','required'=>TRUE,'pattern'=>'/\A[0-9a-f]{64}\z/D']];
const REPORT_EXTRA_FIELDS = [
 'source_class'=>['name'=>'Class','required'=>TRUE,'options'=>['human'=>'Human','agent'=>'Agent','automated'=>'Automated']],
 'source_subtype'=>['name'=>'Subtype','options'=>['script/test_harness'=>'Script','telemetry'=>'Telemetry']],
 'source_identity'=>['name'=>'Identity','required'=>TRUE],'source_name'=>['name'=>'Name','required'=>TRUE],
 'platform'=>['name'=>'Platform','required'=>TRUE,'options'=>['Windows'=>'Windows','Linux'=>'Linux','macOS'=>'macOS','Android'=>'Android','iOS'=>'iOS']],
 'architecture'=>['name'=>'Architecture','required'=>TRUE],'os_version'=>['name'=>'OS','required'=>TRUE],
 'taphle_commit'=>['name'=>'Commit','required'=>TRUE,'pattern'=>'/\A[0-9a-f]{40}\z/D'],
 'artifact_sha256'=>['name'=>'Product hash','required'=>TRUE,'pattern'=>'/\A[0-9a-f]{64}\z/D'],
 'app_artifact_sha256'=>['name'=>'App hash','required'=>TRUE,'pattern'=>'/\A[0-9a-f]{64}\z/D'],
 'build_provenance'=>['name'=>'Provenance','required'=>TRUE],'build_profile'=>['name'=>'Profile','required'=>TRUE,'options'=>['debug'=>'Debug','release'=>'Release']],
 'taphle_release'=>['name'=>'Release'],'release_channel'=>['name'=>'Channel','required'=>TRUE,'options'=>['normal_release'=>'Release','development'=>'Development']],
 'verification_type'=>['name'=>'Verification','required'=>TRUE,'options'=>['compatibility'=>'Compatibility','release_verification'=>'Release verification']],
 'release_version'=>['name'=>'Release version'],'test_run_id'=>['name'=>'Run ID','required'=>TRUE],
 'tested_at'=>['name'=>'Tested','required'=>TRUE,'pattern'=>'/\A\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\z/D'],
 'result'=>['name'=>'Result','required'=>TRUE,'options'=>['completed'=>'Completed','failed'=>'Failed','crashed'=>'Crashed']],
 'evidence_description'=>['name'=>'Evidence','required'=>TRUE],'crash_evidence'=>['name'=>'Crash evidence'],
 'visual_output'=>['name'=>'Visual','required'=>TRUE,'options'=>['meaningful'=>'Meaningful','none'=>'None']],
 'telemetry_consent'=>['name'=>'Consent','options'=>['yes'=>'Yes']],'duration_seconds'=>['name'=>'Duration'],'execution_states'=>['name'=>'States'],
 'termination'=>['name'=>'Termination'],'logs'=>['name'=>'Logs'],'cpu'=>['name'=>'CPU'],'gpu'=>['name'=>'GPU'],'device'=>['name'=>'Device'],'frontier'=>['name'=>'Frontier'],
];
const RELEASE_REQUIRED_PLATFORMS = ['Windows','Linux','macOS'];
const REPORT_SCREENSHOTS_ALLOWED = TRUE;

require_once __DIR__.'/../include/util.php'; require_once __DIR__.'/../include/queries.php'; require_once __DIR__.'/../include/api.php';
use function hikari_no_yume\touchHLE\app_compatibility_db\{apiApplyTrustedApproval,apiAuthenticateCredential,apiFindAppIdByIdentity,apiFindVersionIdByBuild,apiListApps,apiValidateReleaseQualification,compatibilityStateStarCount,createApp,createDeveloperNote,createReport,createVersion,getAppIcon,initDb,listApps,listDeveloperNotesForApp,listEndUserVersionsForApp,listReportsForApp,listVersionsForApp,mergeVersionInto,printAppForm,printReportForm,query,validateExtraFields,validateReportPolicy};
function same($e,$a,string $m):void{if($e!==$a)throw new RuntimeException("$m expected=".var_export($e,TRUE)." actual=".var_export($a,TRUE));}
function yes(bool $a,string $m):void{if(!$a)throw new RuntimeException($m);} function throws(callable $c,string $m):void{try{$c();}catch(Throwable){return;}throw new RuntimeException($m);}
function png():string{return 'data:image/png;base64,'.base64_encode("\x89PNG\r\n\x1a\nfixture");} function jpeg():string{return 'data:image/jpeg;base64,'.base64_encode("\xFF\xD8\xFF\xD9");}
function versionExtra(string $hash):array{return ['bundle_version'=>'42','short_version'=>'1.2','minimum_os_version'=>'2.0','app_artifact_sha256'=>$hash];}
function evidence(array $o=[]):array{static $run=0;$run++;return array_replace(['source_class'=>'agent','source_identity'=>'agent:test','source_name'=>'Test agent','platform'=>'Windows','architecture'=>'x86_64','os_version'=>'11 24H2','taphle_commit'=>str_repeat('a',40),'artifact_sha256'=>str_repeat('b',64),'app_artifact_sha256'=>str_repeat('c',64),'build_provenance'=>'workflow 123 immutable candidate','build_profile'=>'release','taphle_release'=>'1.2.3','release_channel'=>'normal_release','verification_type'=>'compatibility','test_run_id'=>'run-'.$run,'tested_at'=>'2026-09-26T12:00:00Z','result'=>'completed','evidence_description'=>'Visible app window demonstrates the frontier.','visual_output'=>'meaningful','frontier'=>'core loop'],$o);}

initDb();global $db;$db->exec((string)file_get_contents(__DIR__.'/../schema.sql'));
query("INSERT INTO users(user_id,external_user_id,external_username) VALUES(1,'agent:test','agent:test'),(2,'github:human','github:human'),(3,'agent:owner','agent:owner')");
same(['identity'=>'agent:external','trusted'=>FALSE],apiAuthenticateCredential('ordinary-token'),'ordinary credential');same(['identity'=>'agent:owner','trusted'=>TRUE],apiAuthenticateCredential('trusted-token'),'trusted credential');
$states=['?????'=>0,'*XXXX'=>1,'*????'=>1,'**XXX'=>2,'**???'=>2,'***XX'=>3,'***??'=>3,'****X'=>4,'****?'=>4,'*****'=>5];foreach($states as $state=>$stars)same($stars,compatibilityStateStarCount($state),"valid $state");foreach(['','*****?','*X???','XX***','????*','******','⭐⭐⭐⭐⭐']as$state)same(NULL,compatibilityStateStarCount($state),"invalid $state");
$app=['created_by'=>1,'name'=>'Display Name','extra'=>['bundle_identifier'=>'com.example.game','developer_publisher'=>'Example']];same(NULL,createApp($app),'icon required');$app['icon']=png();$appId=createApp($app);yes(is_int($appId),'app created');yes(getAppIcon($appId)!==NULL,'icon stored');same($appId,apiFindAppIdByIdentity(['bundle_identifier'=>'COM.EXAMPLE.GAME']),'canonical case-insensitive identity');$duplicate=$app;$duplicate['name']='Marketing Rename';throws(fn()=>createApp($duplicate),'duplicate display rename prevented');
$hashA=str_repeat('c',64);$hashB=str_repeat('d',64);$versionId=createVersion(['created_by'=>1,'app_id'=>$appId,'name'=>'1.2','extra'=>versionExtra($hashA)]);yes(is_int($versionId),'version created');same($versionId,apiFindVersionIdByBuild($appId,versionExtra($hashA)),'version matched by build/hash');same(NULL,apiFindVersionIdByBuild($appId,versionExtra($hashB)),'different artifact distinct');$versionB=createVersion(['created_by'=>1,'app_id'=>$appId,'name'=>'same label','extra'=>versionExtra($hashB)]);yes(is_int($versionB)&&$versionB!==$versionId,'same build different hash stored');throws(fn()=>createVersion(['created_by'=>1,'app_id'=>$appId,'name'=>'rename','extra'=>versionExtra($hashA)]),'duplicate version provenance prevented');yes(!mergeVersionInto($versionB,$versionId),'version merge rejects different artifact provenance');
$agent=evidence();yes(!validateReportPolicy('***??',$agent,FALSE),'agent screenshot required');yes(!validateReportPolicy('***??',array_replace($agent,['evidence_description'=>'']),TRUE),'agent evidence description required');yes(validateReportPolicy('***??',$agent,TRUE),'agent establishes three');yes(!validateReportPolicy('****?',$agent,TRUE),'agent four rejected');yes(!validateReportPolicy('***??',array_replace($agent,['taphle_release'=>'']),TRUE),'normal release identity required');yes(!validateReportPolicy('***??',array_replace($agent,['tested_at'=>'2026-99-99T12:00:00Z']),TRUE),'invalid UTC date rejected');$human=evidence(['source_class'=>'human','source_identity'=>'github:human','source_name'=>'Human']);yes(validateReportPolicy('*****',$human,FALSE),'human establishes five');$script=evidence(['source_class'=>'automated','source_subtype'=>'script/test_harness']);yes(!validateReportPolicy('***??',$script,FALSE),'visual script screenshot required');yes(validateReportPolicy('***??',$script,TRUE),'script threshold accepted');yes(!validateReportPolicy('****?',$script,TRUE),'automated four rejected');$telemetry=evidence(['source_class'=>'automated','source_subtype'=>'telemetry','telemetry_consent'=>'yes','visual_output'=>'none']);yes(validateReportPolicy('*????',$telemetry,FALSE),'consented telemetry execution accepted');yes(!validateReportPolicy('*XXXX',$telemetry,FALSE),'telemetry cannot claim higher levels failed');yes(!validateReportPolicy('**???',$telemetry,FALSE),'telemetry playability rejected');yes(!validateReportPolicy('*????',array_replace($telemetry,['telemetry_consent'=>'']),FALSE),'telemetry consent required');yes(!validateReportPolicy('*XXXX',evidence(['result'=>'crashed','crash_evidence'=>'']),TRUE),'crash evidence required');yes(validateReportPolicy('*XXXX',evidence(['result'=>'crashed','crash_evidence'=>'crash-log']),TRUE),'crash evidence accepted');$releaseEvidence=evidence(['verification_type'=>'release_verification','release_version'=>'1.2.3']);yes(validateReportPolicy('***??',$releaseEvidence,TRUE),'valid release verification accepted');yes(!validateReportPolicy('***??',array_replace($releaseEvidence,['taphle_release'=>'1.2.4']),TRUE),'release identity mismatch rejected');yes(!validateExtraFields(REPORT_EXTRA_FIELDS,evidence(['taphle_commit'=>'abc'])),'bad commit rejected');yes(!validateExtraFields(REPORT_EXTRA_FIELDS,evidence(['artifact_sha256'=>str_repeat('z',64)])),'bad product hash rejected');yes(!validateExtraFields(REPORT_EXTRA_FIELDS,evidence(['app_artifact_sha256'=>str_repeat('z',64)])),'bad app hash rejected');
foreach(array_keys($states)as$i=>$state){$isHuman=$states[$state]>3;$extra=$isHuman?array_replace($human,['test_run_id'=>'valid-'.$i]):evidence(['test_run_id'=>'valid-'.$i]);$id=createReport(['created_by'=>$isHuman?2:1,'version_id'=>$versionId,'compatibility_state'=>$state,'extra'=>$extra,'screenshot'=>$isHuman?'':jpeg()]);yes(is_int($id),"persist $state");}foreach(['*X???','????*','******']as$i=>$state)same(NULL,createReport(['created_by'=>1,'version_id'=>$versionId,'compatibility_state'=>$state,'extra'=>evidence(['test_run_id'=>'invalid-'.$i]),'screenshot'=>jpeg()]),"reject $state");same(NULL,createReport(['created_by'=>1,'version_id'=>$versionId,'compatibility_state'=>'***??','extra'=>evidence(['app_artifact_sha256'=>$hashB]),'screenshot'=>jpeg()]),'report/version hash mismatch');$humanId=createReport(['created_by'=>2,'version_id'=>$versionId,'compatibility_state'=>'*****','extra'=>array_replace($human,['test_run_id'=>'human-five']),'screenshot'=>'']);yes(is_int($humanId),'human report stored');throws(fn()=>createReport(['created_by'=>1,'version_id'=>$versionId,'compatibility_state'=>'***??','extra'=>evidence(['test_run_id'=>'valid-0']),'screenshot'=>jpeg()]),'duplicate test run rejected');
$moderatedApp=createApp(['created_by'=>3,'name'=>'Moderated','icon'=>png(),'extra'=>['bundle_identifier'=>'com.example.moderated']]);$moderatedVersion=createVersion(['created_by'=>3,'app_id'=>$moderatedApp,'name'=>'1.0','extra'=>versionExtra($hashA)]);$moderatedReport=createReport(['created_by'=>3,'version_id'=>$moderatedVersion,'compatibility_state'=>'***??','extra'=>evidence(['source_identity'=>'agent:owner','test_run_id'=>'moderation-run']),'screenshot'=>jpeg()]);apiApplyTrustedApproval(FALSE,3,$moderatedApp,TRUE,$moderatedVersion,TRUE,$moderatedReport);same(NULL,query('SELECT approved FROM reports WHERE report_id=:id',[':id'=>$moderatedReport])[0]['approved'],'ordinary credential remains moderated');apiApplyTrustedApproval(TRUE,3,$moderatedApp,TRUE,$moderatedVersion,TRUE,$moderatedReport);yes(query('SELECT approved FROM reports WHERE report_id=:id',[':id'=>$moderatedReport])[0]['approved']!==NULL,'trusted credential approves own hierarchy');
query('UPDATE apps SET approved=datetime(),approved_by=3 WHERE app_id=:id',[':id'=>$appId]);query('UPDATE versions SET approved=datetime(),approved_by=3 WHERE app_id=:id',[':id'=>$appId]);query('UPDATE reports SET approved=datetime(),approved_by=3');$apps=apiListApps();same($appId,$apps[0]['app_id'],'approved app listed');yes(isset($apps[0]['states_by_platform']['Windows']),'platform state exposed');$before=(int)query('SELECT COUNT(*) count FROM reports')[0]['count'];query("INSERT INTO reports(version_id,created,created_by,approved,approved_by,rating,compatibility_state,extra) VALUES(:version,datetime(),1,datetime(),3,2,'**???',:extra)",[':version'=>$versionId,':extra'=>json_encode(evidence(['test_run_id'=>'conflict']))]);same($before+1,(int)query('SELECT COUNT(*) count FROM reports')[0]['count'],'conflict appended without overwrite');$apps=apiListApps();same('**???',$apps[0]['states_by_platform']['Windows'],'same-timestamp API summary uses later report id');
$candidate=['taphle_commit'=>str_repeat('a',40),'artifact_sha256'=>str_repeat('b',64),'build_provenance'=>'workflow 123 immutable candidate','build_profile'=>'release'];$records=[];foreach(RELEASE_REQUIRED_PLATFORMS as $platform)$records[]=array_merge($candidate,['platform'=>$platform]);$records[1]['artifact_sha256']=str_repeat('f',64);yes(apiValidateReleaseQualification($records,RELEASE_REQUIRED_PLATFORMS)['qualified'],'platform artifacts from one candidate qualify');$records[2]['taphle_commit']=str_repeat('e',40);yes(!apiValidateReleaseQualification($records,RELEASE_REQUIRED_PLATFORMS)['qualified'],'mixed candidate rejected');yes(!apiValidateReleaseQualification(array_slice($records,0,2),RELEASE_REQUIRED_PLATFORMS)['qualified'],'missing platform rejected');$noteId=createDeveloperNote(['created_by'=>2,'app_id'=>$appId,'body'=>'Investigate audio']);yes(is_int($noteId),'note attaches without rating');same(NULL,createDeveloperNote(['created_by'=>2,'app_id'=>$appId,'version_id'=>$versionId,'body'=>'ambiguous']),'note requires exactly one target');$trustedNote=createDeveloperNote(['created_by'=>3,'report_id'=>$humanId,'body'=>'Release follow-up'],TRUE);yes(is_int($trustedNote),'trusted scoped note accepted');same(1,(int)query('SELECT COUNT(*) count FROM developer_notes WHERE approved IS NOT NULL')[0]['count'],'trusted note auto-approved');
ob_start();listApps(FALSE);listEndUserVersionsForApp($appId);listVersionsForApp($appId,FALSE,FALSE);listReportsForApp($appId,FALSE,FALSE);listDeveloperNotesForApp($appId,FALSE);printAppForm();printReportForm();$html=(string)ob_get_clean();yes(strpos($html,'Latest released compatibility')!==FALSE,'end-user view renders');yes(strpos($html,'Platform exceptions')!==FALSE,'coarse platform summary renders');yes(strpos($html,'Conflict')!==FALSE,'developer conflict view renders');yes(strpos($html,'App icon')!==FALSE,'manual icon input renders');yes(strpos($html,'compatibility_state')!==FALSE,'ten-state submission control renders');
echo "compatibility model tests passed\n";
